Traceback (most recent call last):
  File "/afs/cern.ch/work/c/cdroin/private/example_DA_study/master_study/scans/dynamic_collapse_new/base_collider/xtrack_0000/gen_3/gen_4/gen_5/5_track.py", line 212, in <module>
    configure_and_track()
  File "/afs/cern.ch/work/c/cdroin/private/example_DA_study/master_study/scans/dynamic_collapse_new/base_collider/xtrack_0000/gen_3/gen_4/gen_5/5_track.py", line 185, in configure_and_track
    collider, config_sim, config_bb = configure_collider(config)
  File "/afs/cern.ch/work/c/cdroin/private/example_DA_study/master_study/scans/dynamic_collapse_new/base_collider/xtrack_0000/gen_3/gen_4/gen_5/5_track.py", line 91, in configure_collider
    collider = xt.Multiline.from_json(config_sim["collider_file"])
  File "/afs/cern.ch/work/c/cdroin/private/example_DA_study/miniforge/lib/python3.10/site-packages/xtrack/multiline/multiline.py", line 168, in from_json
    with open(file, 'r') as fid:
FileNotFoundError: [Errno 2] No such file or directory: '../collider.json'
